# Generated by Django 4.2.11 on 2025-05-12 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('user_type', models.CharField(default='', max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='res_api_use_name_bfc623_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReservationInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=255)),
                ('reservation_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to='res_api.user')),
            ],
        ),
    ]
