# Generated by Django 5.2 on 2025-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_api', '0002_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['owner', 'restaurant_name'], name='res_api_men_owner_i_cd48fb_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['category'], name='res_api_men_categor_e4942d_idx'),
        ),
    ]
