# Generated by Django 4.2.4 on 2025-05-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_api', '0003_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationinfo',
            old_name='name',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='number_of_ppl',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='restuarant_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
